### ISSUE TITLE
cuda out of memory 

### ISSUE THREAD

**Issue by Freeverc** [Anttwo/SuGaR#40]
Is there any parameter can reduce cuda memory ,  please? 
"cuda out of memory"  for 400+ images on 24G cuda device 3090

**Comment by yuedajiong** [comment]
My GPU is OK:  12G Beggar's，700*1200 size,  240 images.  

1.  reduce image size
2.  reduce gauss-points  (important, BUT maybe your images are very complex.)

**Comment by cubantonystark** [comment]
if the error is directly related to pytorch reserving GPU memory, you can try adding:

os.environ["PYTORCH_NO_CUDA_MEMORY_CACHING"]= "1"

and clearing the cache with

torch.cuda.empty_cache() 

Hope that helps

**Comment by JuliusQv** [comment]
suagr_model will load the dataset to the GPU by default, which will consume a lot of GPU memory.

So,  you can try the fllowing steps:
1. modified this [code](https://github.com/Anttwo/SuGaR/blob/72b9baa942593a8d3d7ef205288788821cedb1e8/sugar_scene/cameras.py#L100C65-L100C65),  `image_height=image_height, image_width=image_width, data_device='cpu')`
2. move the image to cuda during training process, modified this [code](https://github.com/Anttwo/SuGaR/blob/72b9baa942593a8d3d7ef205288788821cedb1e8/sugar_trainers/coarse_sdf.py#L521C81-L521C81)  `gt_image = nerfmodel.get_gt_image(camera_indices=camera_indices).cuda()`
3. same action in `coarse_density.py`   and  `refined.py`

By use this method,
2000+images on my 24GB device 4090 is okay.

Hope this help.

**Comment by cubantonystark** [comment]
Gentlemen,

After implementing this suggestion, I get the following error now:

scales 0.005
quaternions 0.001
Densifier initialized.
Using loss function: l1+dssim
Traceback (most recent call last):
  File "/home/reynel/SuGaR/train.py", line 118, in <module>
    coarse_sugar_path = coarse_training_with_sdf_regularization(coarse_args)
  File "/home/reynel/SuGaR/sugar_trainers/coarse_sdf.py", line 526, in coarse_training_with_sdf_regularization
    loss = loss_fn(pred_rgb, gt_rgb)
  File "/home/reynel/SuGaR/sugar_trainers/coarse_sdf.py", line 447, in loss_fn
    return (1.0 - dssim_factor) * l1_loss(pred_rgb, gt_rgb) + dssim_factor * (1.0 - ssim(pred_rgb, gt_rgb))
  File "/home/reynel/SuGaR/sugar_utils/loss_utils.py", line 18, in l1_loss
    return torch.abs((network_output - gt)).mean()
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

Any help will be greatly appreciated.

**Comment by cubantonystark** [comment]
Please disregard previous email, I had mistyped the suggestion and formatted the parentheses in …camera_indices).cuda() as …camera_indices.cuda())

My mistake. I’m rerunning my datasets again now. Will report back with results. Anttwo, please let me know if you would like me to share results of my dataset with you to showcase quality.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by cubantonystark** [comment]
Julius, Are you reducing image size bwfore processing?  Got OOM again.  My dataset is only 26 images at 1900x1423.Best regards,Reynel RodriguezOn Dec 22, 2023 01:40, Reynel Rodriguez ***@***.***> wrote:

Please disregard previous email, I had mistyped the suggestion and formatted the parentheses in …camera_indices).cuda() as …camera_indices.cuda())
 
My mistake. I’m rerunning my datasets again now. Will report back with results. Anttwo, please let me know if you would like me to share results of my dataset with you to showcase quality.
 
Sent from 
Mail for Windows
 

From: julius
Sent: Thursday, December 21, 2023 9:09 PM
To: Anttwo/SuGaR
Cc: Cuban Tony Stark; 
Comment
Subject: Re: [Anttwo/SuGaR] cuda out of memory (Issue #40)

 
suagr_model will load the dataset to the GPU by default, which will consume a lot of GPU memory.
So, you can try the fllowing steps:

modified this 
code, image_height=image_height, image_width=image_width, data_device='cpu')
move the image to cuda during training process, modified this 
code gt_image = nerfmodel.get_gt_image(camera_indices=camera_indices).cuda()
same action in coarse_density.py and
refined.py
By use this method,
2000+images on my 24GB device 4090 is okay.
Hope this help.
—
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
You are receiving this because you commented.Message
 ID: ***@***.***>

**Comment by JuliusQv** [comment]
> Are you reducing image size bwfore processing?  Got OOM again.  My dataset is only 26 images at 1900x1423.
No，I did not reduce the images size.
What GPU are you using and how much memory?
And which step does OOM happen?
In my experiments, I found that the final texture mesh extraction stage requires a large amount of GPU memory.

**Comment by JuliusQv** [comment]
> Julius, Are you reducing image size bwfore processing?  Got OOM again.  My dataset is only 26 images at 1900x1423.Best regards,Reynel RodriguezOn Dec 22, 2023 01:40, Reynel Rodriguez ***@***.***> wrote: Please disregard previous email, I had mistyped the suggestion and formatted the parentheses in …camera_indices).cuda() as …camera_indices.cuda())   My mistake. I’m rerunning my datasets again now. Will report back with results. Anttwo, please let me know if you would like me to share results of my dataset with you to showcase quality.   Sent from Mail for Windows   From: julius Sent: Thursday, December 21, 2023 9:09 PM To: Anttwo/SuGaR Cc: Cuban Tony Stark; Comment Subject: Re: [Anttwo/SuGaR] cuda out of memory (Issue #40)   suagr_model will load the dataset to the GPU by default, which will consume a lot of GPU memory. So, you can try the fllowing steps: modified this code, image_height=image_height, image_width=image_width, data_device='cpu') move the image to cuda during training process, modified this code gt_image = nerfmodel.get_gt_image(camera_indices=camera_indices).cuda() same action in coarse_density.py and refined.py By use this method, 2000+images on my 24GB device 4090 is okay. Hope this help. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

Are you reducing image size bwfore processing? Got OOM again. My dataset is only 26 images at 1900x1423.
No，I did not reduce the images size.
What GPU are you using and how much memory?
And which step does OOM happen?
In my experiments, I found that the final texture mesh extraction stage requires a large amount of GPU memory.

**Comment by JuliusQv** [comment]
> Julius, Are you reducing image size bwfore processing?  Got OOM again.  My dataset is only 26 images at 1900x1423.Best regards,Reynel RodriguezOn Dec 22, 2023 01:40, Reynel Rodriguez ***@***.***> wrote: Please disregard previous email, I had mistyped the suggestion and formatted the parentheses in …camera_indices).cuda() as …camera_indices.cuda())   My mistake. I’m rerunning my datasets again now. Will report back with results. Anttwo, please let me know if you would like me to share results of my dataset with you to showcase quality.   Sent from Mail for Windows   From: julius Sent: Thursday, December 21, 2023 9:09 PM To: Anttwo/SuGaR Cc: Cuban Tony Stark; Comment Subject: Re: [Anttwo/SuGaR] cuda out of memory (Issue #40)   suagr_model will load the dataset to the GPU by default, which will consume a lot of GPU memory. So, you can try the fllowing steps: modified this code, image_height=image_height, image_width=image_width, data_device='cpu') move the image to cuda during training process, modified this code gt_image = nerfmodel.get_gt_image(camera_indices=camera_indices).cuda() same action in coarse_density.py and refined.py By use this method, 2000+images on my 24GB device 4090 is okay. Hope this help. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

No，I did not reduce the images size.  
What GPU are you using and how much memory?
And which step does OOM happen?
In my experiments, I found that the final texture mesh extraction stage requires a large amount of GPU memory.

**Comment by cubantonystark** [comment]
Thats the step where im sruck and i get the OOM. Best regards,Reynel RodriguezOn Dec 22, 2023 04:16, julius ***@***.***> wrote:

Julius, Are you reducing image size bwfore processing?  Got OOM again.  My dataset is only 26 images at 1900x1423.Best regards,Reynel RodriguezOn Dec 22, 2023 01:40, Reynel Rodriguez @.> wrote: Please disregard previous email, I had mistyped the suggestion and formatted the parentheses in …camera_indices).cuda() as …camera_indices.cuda())   My mistake. I’m rerunning my datasets again now. Will report back with results. Anttwo, please let me know if you would like me to share results of my dataset with you to showcase quality.   Sent from Mail for Windows   From: julius Sent: Thursday, December 21, 2023 9:09 PM To: Anttwo/SuGaR Cc: Cuban Tony Stark; Comment Subject: Re: [Anttwo/SuGaR] cuda out of memory (Issue #40)   suagr_model will load the dataset to the GPU by default, which will consume a lot of GPU memory. So, you can try the fllowing steps: modified this code, image_height=image_height, image_width=image_width, data_device='cpu') move the image to cuda during training process, modified this code gt_image = nerfmodel.get_gt_image(camera_indices=camera_indices).cuda() same action in coarse_density.py and refined.py By use this method, 2000+images on my 24GB device 4090 is okay. Hope this help. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.>

No，I did not reduce the images size.
What GPU are you using and how much memory?
And which step does OOM happen?
In my experiments, I found that the final texture mesh extraction stage requires a large amount of GPU memory.

**Comment by cubantonystark** [comment]
I am using an RTX 4090 with 16Gb. On an Alienware M18 with 64 Gb RAM. I Also ran it on an Asus Razer Blade 16 with 32 Gb RAM and RTX 4090 and got OOM at that stage as well. Best regards,Reynel RodriguezOn Dec 22, 2023 04:16, julius ***@***.***> wrote:

Julius, Are you reducing image size bwfore processing?  Got OOM again.  My dataset is only 26 images at 1900x1423.Best regards,Reynel RodriguezOn Dec 22, 2023 01:40, Reynel Rodriguez @.> wrote: Please disregard previous email, I had mistyped the suggestion and formatted the parentheses in …camera_indices).cuda() as …camera_indices.cuda())   My mistake. I’m rerunning my datasets again now. Will report back with results. Anttwo, please let me know if you would like me to share results of my dataset with you to showcase quality.   Sent from Mail for Windows   From: julius Sent: Thursday, December 21, 2023 9:09 PM To: Anttwo/SuGaR Cc: Cuban Tony Stark; Comment Subject: Re: [Anttwo/SuGaR] cuda out of memory (Issue #40)   suagr_model will load the dataset to the GPU by default, which will consume a lot of GPU memory. So, you can try the fllowing steps: modified this code, image_height=image_height, image_width=image_width, data_device='cpu') move the image to cuda during training process, modified this code gt_image = nerfmodel.get_gt_image(camera_indices=camera_indices).cuda() same action in coarse_density.py and refined.py By use this method, 2000+images on my 24GB device 4090 is okay. Hope this help. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.>

No，I did not reduce the images size.
What GPU are you using and how much memory?
And which step does OOM happen?
In my experiments, I found that the final texture mesh extraction stage requires a large amount of GPU memory.

**Comment by WN-Wolf** [comment]
> suagr_model will load the dataset to the GPU by default, which will consume a lot of GPU memory.
> 
> So, you can try the fllowing steps:
> 
> 1. modified this [code](https://github.com/Anttwo/SuGaR/blob/72b9baa942593a8d3d7ef205288788821cedb1e8/sugar_scene/cameras.py#L100C65-L100C65),  `image_height=image_height, image_width=image_width, data_device='cpu')`
> 2. move the image to cuda during training process, modified this [code](https://github.com/Anttwo/SuGaR/blob/72b9baa942593a8d3d7ef205288788821cedb1e8/sugar_trainers/coarse_sdf.py#L521C81-L521C81)  `gt_image = nerfmodel.get_gt_image(camera_indices=camera_indices).cuda()`
> 3. same action in `coarse_density.py`   and  `refined.py`
> 
> By use this method, 2000+images on my 24GB device 4090 is okay.
> 
> Hope this help.

It's very useful, thanks!!!

**Comment by Ryan-ZL-Lin** [comment]
> suagr_model will load the dataset to the GPU by default, which will consume a lot of GPU memory.
> 
> So, you can try the fllowing steps:
> 
> 1. modified this [code](https://github.com/Anttwo/SuGaR/blob/72b9baa942593a8d3d7ef205288788821cedb1e8/sugar_scene/cameras.py#L100C65-L100C65),  `image_height=image_height, image_width=image_width, data_device='cpu')`
> 2. move the image to cuda during training process, modified this [code](https://github.com/Anttwo/SuGaR/blob/72b9baa942593a8d3d7ef205288788821cedb1e8/sugar_trainers/coarse_sdf.py#L521C81-L521C81)  `gt_image = nerfmodel.get_gt_image(camera_indices=camera_indices).cuda()`
> 3. same action in `coarse_density.py`   and  `refined.py`
> 
> By use this method, 2000+images on my 24GB device 4090 is okay.
> 
> Hope this help.

I changed the code accordingly, although the OOM issue was disappeared, I encounter a new issue with "Killed" message, here is the log, do you have any idea what's happening? 
I'm using RTX 4080 12GB GPU to run 1000+ images with 1472x1472 


```
(sugar) ryan_lin@RyanLegionPro7i:/mnt/c/Users/lzlal/SuGaR$ python train.py -s /mnt/c/Users/lzlal/gaussian_splatting/data/BLK3_Room_1S_8_R1/ -c /mnt/c/Users/lzlal/gaussian_splatting/output/BLK3_Room_1S_8_R1/ -r density
Will export a UV-textured mesh as an .obj file.
Will export a ply file with the refined 3D Gaussians at the end of the training.
Changing sh_levels to match the loaded model: 4
-----Parsed parameters-----
Source path: /mnt/c/Users/lzlal/gaussian_splatting/data/BLK3_Room_1S_8_R1/
   > Content: 10
Gaussian Splatting checkpoint path: /mnt/c/Users/lzlal/gaussian_splatting/output/BLK3_Room_1S_8_R1/
   > Content: 4
SUGAR checkpoint path: ./output/coarse/BLK3_Room_1S_8_R1/sugarcoarse_3Dgs7000_densityestim02_sdfnorm02/
Iteration to load: 7000
Output directory: ./output/coarse/BLK3_Room_1S_8_R1
SDF estimation factor: 0.2
SDF better normal factor: 0.2
Eval split: True
---------------------------
Using device: 0
|===========================================================================|
|                  PyTorch CUDA memory summary, device ID 0                 |
|---------------------------------------------------------------------------|
|            CUDA OOMs: 0            |        cudaMalloc retries: 0         |
|===========================================================================|
|        Metric         | Cur Usage  | Peak Usage | Tot Alloc  | Tot Freed  |
|---------------------------------------------------------------------------|
| Allocated memory      |      0 B   |      0 B   |      0 B   |      0 B   |
|       from large pool |      0 B   |      0 B   |      0 B   |      0 B   |
|       from small pool |      0 B   |      0 B   |      0 B   |      0 B   |
|---------------------------------------------------------------------------|
| Active memory         |      0 B   |      0 B   |      0 B   |      0 B   |
|       from large pool |      0 B   |      0 B   |      0 B   |      0 B   |
|       from small pool |      0 B   |      0 B   |      0 B   |      0 B   |
|---------------------------------------------------------------------------|
| Requested memory      |      0 B   |      0 B   |      0 B   |      0 B   |
|       from large pool |      0 B   |      0 B   |      0 B   |      0 B   |
|       from small pool |      0 B   |      0 B   |      0 B   |      0 B   |
|---------------------------------------------------------------------------|
| GPU reserved memory   |      0 B   |      0 B   |      0 B   |      0 B   |
|       from large pool |      0 B   |      0 B   |      0 B   |      0 B   |
|       from small pool |      0 B   |      0 B   |      0 B   |      0 B   |
|---------------------------------------------------------------------------|
| Non-releasable memory |      0 B   |      0 B   |      0 B   |      0 B   |
|       from large pool |      0 B   |      0 B   |      0 B   |      0 B   |
|       from small pool |      0 B   |      0 B   |      0 B   |      0 B   |
|---------------------------------------------------------------------------|
| Allocations           |       0    |       0    |       0    |       0    |
|       from large pool |       0    |       0    |       0    |       0    |
|       from small pool |       0    |       0    |       0    |       0    |
|---------------------------------------------------------------------------|
| Active allocs         |       0    |       0    |       0    |       0    |
|       from large pool |       0    |       0    |       0    |       0    |
|       from small pool |       0    |       0    |       0    |       0    |
|---------------------------------------------------------------------------|
| GPU reserved segments |       0    |       0    |       0    |       0    |
|       from large pool |       0    |       0    |       0    |       0    |
|       from small pool |       0    |       0    |       0    |       0    |
|---------------------------------------------------------------------------|
| Non-releasable allocs |       0    |       0    |       0    |       0    |
|       from large pool |       0    |       0    |       0    |       0    |
|       from small pool |       0    |       0    |       0    |       0    |
|---------------------------------------------------------------------------|
| Oversize allocations  |       0    |       0    |       0    |       0    |
|---------------------------------------------------------------------------|
| Oversize GPU segments |       0    |       0    |       0    |       0    |
|===========================================================================|


Loading config /mnt/c/Users/lzlal/gaussian_splatting/output/BLK3_Room_1S_8_R1/...
Performing train/eval split...
Found image extension .jpg
Killed
(sugar) ryan_lin@RyanLegionPro7i:/mnt/c/Users/lzlal/SuGaR$
```

**Comment by MagicJoeXZ** [comment]
> suagr_model will load the dataset to the GPU by default, which will consume a lot of GPU memory.
>
> So, you can try the fllowing steps:
>
>modified this [code](https://github.com/Anttwo/SuGaR/blob/72b9baa942593a8d3d7ef205288788821cedb1e8/sugar_scene/cameras.py#L100C65-L100C65), image_height=image_height, image_width=image_width, data_device='cpu')
move the image to cuda during training process, modified this [code](https://github.com/Anttwo/SuGaR/blob/72b9baa942593a8d3d7ef205288788821cedb1e8/sugar_trainers/coarse_sdf.py#L521C81-L521C81) gt_image = nerfmodel.get_gt_image(camera_indices=camera_indices).cuda()
same action in coarse_density.py and refined.py
By use this method, 2000+images on my 24GB device 4090 is okay.
>
>Hope this help.

Verified this works well! 

Besides the suggestion above, i also change [device type here](https://github.com/Anttwo/SuGaR/blob/9c059ac9754a7bc058c17788181310376bd7981f/sugar_scene/gs_model.py#L25) from cuda to cpu
